import type { ScoreResult } from '../scoring/types';

export type { ScoreResult };

// A niche seed from the curated library (shipped with the codebase).
export interface CuratedSeed {
  title: string;
  category: string;
  rationale: string;
}

// A niche seed generated by the AI brainstorm pass ("Suggest More Niches").
export interface GeneratedSeed {
  title: string;
  rationale: string;
}

// A seed that has been scored via batch researchTitle().
export interface ScoredNiche {
  seed: string;
  rationale: string;
  category: string;
  demand: ScoreResult;
  competition: ScoreResult;
  /** (demand.score + competition.score) / 2 — decision 8 */
  combinedScore: number;
  marketSize: {
    exactAngleCount: number;
    totalCount: number;
  };
  /** Top 3 exact-angle-match listing titles from Etsy */
  exampleListings: string[];
  /** Min/max price of exact-angle listings, null if none found */
  priceRange: { min: number; max: number } | null;
}

// The complete result of a discovery run (ephemeral — not persisted in v1).
export interface DiscoveryResult {
  niches: ScoredNiche[];
  scoredCount: number;
  elapsedMs: number;
}
